{{--

  @if( $practise['type'] == "one_blank_table" || $practise['type'] == "two_blank_table" || $practise['type'] == "three_blank_table" || $practise['type'] == "four_blank_table" || $practise['type'] == "five_blank_table" || $practise['type'] == "six_blank_table" || $practise['type'] == "two_blank_table_listening" || $practise['type'] == "three_blank_table_listening" || $practise['type'] == "four_blank_table_listening" || $practise['type'] == "five_blank_table_listening" || $practise['type'] == "six_blank_table_listening"  || $practise['type'] == "two_blanks_table_listening" || $practise['type'] == "three_blanks_table_listening" || $practise['type'] == "four_blanks_table_listening" || $practise['type'] == "five_blanks_table_listening" || $practise['type'] == "six_blanks_table_listening" || $practise['type'] == "one_table_option" || $practise['type'] == "two_table_option" || $practise['type'] == "three_table_option" || $practise['type'] == "four_table_option" || $practise['type'] == "five_table_option" || $practise['type'] == "six_table_option" || $practise['type'] == "one_blank_table_speaking" || $practise['type'] == "one_table_option_speaking" || $practise['type'] == "one_blank_table_speaking_up" || $practise['type'] == "two_blank_table_speaking" || $practise['type'] == "two_table_option_speaking" || $practise['type'] == "two_blank_table_speaking_up" ||  $practise['type'] == "three_blank_table_speaking" || $practise['type'] == "three_table_option_speaking" || $practise['type'] == "three_blank_table_speaking_up" || $practise['type'] == "four_blank_table_speaking" || $practise['type'] == "four_table_option_speaking" || $practise['type'] == "four_blank_table_speaking_up" || $practise['type'] == "five_blank_table_speaking" || $practise['type'] == "five_table_option_speaking" || $practise['type'] == "five_blank_table_speaking_up" || $practise['type'] == "six_blank_table_speaking" || $practise['type'] == "six_table_option_speaking" || $practise['type'] == "six_blank_table_speaking_up" || $practise['type'] == "seven_blank_table_speaking" || $practise['type'] == "seven_table_option_speaking" || $practise['type'] == "seven_blank_table_speaking_up" || $practise['type'] == "eight_blank_table_speaking" || $practise['type'] == "eight_table_option_speaking" || $practise['type'] == "eight_blank_table_speaking_up" || $practise['type'] == "nine_blank_table_speaking" || $practise['type'] == "nine_table_option_speaking" || $practise['type'] == "nine_blank_table_speaking_up" || $practise['type'] == "ten_blank_table_speaking" || $practise['type'] == "ten_table_option_speaking" || $practise['type'] == "ten_blank_table_speaking_up" || $practise['type'] == "one_table_option_listening" || $practise['type'] == "two_table_option_listening" || $practise['type'] == "three_table_option_listening" || $practise['type'] == "four_table_option_listening" || $practise['type'] == "five_table_option_listening" || $practise['type'] == "six_table_option_listening" || $practise['type'] == "six_blank_table_true_false" || $practise['type'] == "two_table_option_speaking_up"  || $practise['type'] == "two_blank_table_up_writing_at_end_up"  || $practise['type'] == "writing_at_end_four_blanks_table"  || $practise['type'] == "writing_at_end_up_four_blanks_table")
  --}}

@if($practise['type'] == "one_blank_table")
  @include('practice.one_blank_table')
@elseif($practise['type'] == "two_blank_table")
  @include('practice.two_blank_table')
@elseif($practise['type'] == "three_blank_table")
  @include('practice.three_blank_table')
@elseif($practise['type'] == "four_blank_table")
  @include('practice.four_blank_table')
@elseif($practise['type'] == "five_blank_table")
  @include('practice.five_blank_table')
@elseif($practise['type'] == "six_blank_table")
  @include('practice.six_blank_table')
@elseif($practise['type'] == "two_blank_table_listening")
  @include('practice.two_blanks_table_listening')
@elseif($practise['type'] == "three_blank_table_listening")
  @include('practice.three_blank_table_listening')
@elseif($practise['type'] == "four_blank_table_listening")
  @include('practice.four_blank_table_listening')
@elseif($practise['type'] == "five_blank_table_listening")
  @include('practice.five_blank_table_listening')
@elseif($practise['type'] == "six_blank_table_listening")
  @include('practice.six_blank_table_listening')
@elseif($practise['type'] == "two_blanks_table_listening")
  @include('practice.two_blanks_table_listening')
@elseif($practise['type'] == "three_blanks_table_listening")
  @include('practice.three_blanks_table_listening')
@elseif($practise['type'] == "four_blanks_table_listening")
  @include('practice.four_blanks_table_listening')
@elseif($practise['type'] == "five_blanks_table_listening")
  @include('practice.five_blanks_table_listening')
@elseif($practise['type'] == "six_blanks_table_listening")
  @include('practice.six_blanks_table_listening')
@elseif($practise['type'] == "one_table_option")
  @include('practice.one_table_option')
@elseif($practise['type'] == "two_table_option")
  @include('practice.two_table_option')
@elseif($practise['type'] == "three_table_option")
  @include('practice.three_table_option')
@elseif($practise['type'] == "four_table_option")
  @include('practice.four_table_option')
@elseif($practise['type'] == "five_table_option")
  @include('practice.five_table_option')
@elseif($practise['type'] == "six_table_option")
  @include('practice.six_table_option')
@elseif($practise['type'] == "one_blank_table_speaking")
  @include('practice.one_blank_table_speaking')
@elseif($practise['type'] == "one_table_option_speaking")
  @include('practice.one_table_option_speaking')
@elseif($practise['type'] == "two_blank_table_speaking")
  @include('practice.two_blank_table_speaking')
@elseif($practise['type'] == "one_blank_table_speaking_up")
  @include('practice.one_blank_table_speaking_up')
@elseif($practise['type'] == "two_table_option_speaking")
  @include('practice.two_table_option_speaking')
@elseif($practise['type'] == "two_blank_table_speaking_up")
  @include('practice.two_blank_table_speaking_up')
@elseif($practise['type'] == "three_blank_table_speaking")
  @include('practice.three_blank_table_speaking')
@elseif($practise['type'] == "three_table_option_speaking")
  @include('practice.three_table_option_speaking')
@elseif($practise['type'] == "three_blank_table_speaking_up")
  @include('practice.three_blank_table_speaking_up_new')
@elseif($practise['type'] == "four_blank_table_speaking")
  @include('practice.four_blank_table_speaking')
@elseif($practise['type'] == "four_table_option_speaking")
  @include('practice.four_table_option_speaking')
@elseif($practise['type'] == "four_blank_table_speaking_up")
  @include('practice.four_blank_table_speaking_up')
@elseif($practise['type'] == "five_blank_table_speaking")
  @include('practice.five_blank_table_speaking')
@elseif($practise['type'] == "five_table_option_speaking")
  @include('practice.five_table_option_speaking')
@elseif($practise['type'] == "five_blank_table_speaking_up")
  @include('practice.five_blank_table_speaking_up')
@elseif($practise['type'] == "six_blank_table_speaking")
  @include('practice.six_blank_table_speaking')
@elseif($practise['type'] == "six_table_option_speaking")
  @include('practice.six_table_option_speaking')


@elseif($practise['type'] == "six_blank_table_speaking_up")
  @include('practice.six_blank_table_speaking_up')
@elseif($practise['type'] == "seven_blank_table_speaking")
  @include('practice.seven_blank_table_speaking')
@elseif($practise['type'] == "seven_table_option_speaking")
  @include('practice.seven_table_option_speaking')


@elseif($practise['type'] == "seven_blank_table_speaking_up")
  @include('practice.seven_blank_table_speaking_up')
@elseif($practise['type'] == "eight_blank_table_speaking")
  @include('practice.eight_blank_table_speaking')
@elseif($practise['type'] == "eight_table_option_speaking")
  @include('practice.eight_table_option_speaking')
@elseif($practise['type'] == "eight_blank_table_speaking_up")
  @include('practice.eight_blank_table_speaking_up')
@elseif($practise['type'] == "nine_blank_table_speaking")
  @include('practice.nine_blank_table_speaking')
@elseif($practise['type'] == "nine_table_option_speaking")
  @include('practice.nine_table_option_speaking')
@elseif($practise['type'] == "nine_blank_table_speaking_up")
  @include('practice.nine_blank_table_speaking_up')
@elseif($practise['type'] == "ten_blank_table_speaking")
  @include('practice.ten_blank_table_speaking')
@elseif($practise['type'] == "ten_table_option_speaking")
  @include('practice.ten_table_option_speaking')
@elseif($practise['type'] == "ten_blank_table_speaking_up")
  @include('practice.ten_blank_table_speaking_up')
@elseif($practise['type'] == "one_table_option_listening")
  @include('practice.one_table_option_listening')
@elseif($practise['type'] == "two_table_option_listening")
  @include('practice.two_table_option_listening')
@elseif($practise['type'] == "three_table_option_listening")
  @include('practice.three_table_option_listening')
@elseif($practise['type'] == "four_table_option_listening")
  @include('practice.four_table_option_listening')
@elseif($practise['type'] == "five_table_option_listening")
  @include('practice.five_table_option_listening')
@elseif($practise['type'] == "six_table_option_listening")
  @include('practice.six_table_option_listening')
@elseif($practise['type'] == "six_blank_table_true_false")
  @include('practice.six_blank_table_true_false')
@elseif($practise['type'] == "two_table_option_speaking_up")
  @include('practice.two_table_option_speaking_up')
@elseif($practise['type'] == "two_blank_table_up_writing_at_end_up")
  @include('practice.two_blank_table_up_writing_at_end_up')
@elseif($practise['type'] == "writing_at_end_four_blanks_table")
  @include('practice.writing_at_end_up_four_blanks_table')
@elseif($practise['type'] == "writing_at_end_up_four_blanks_table")
  @include('practice.writing_at_end_up_four_blanks_table')
@elseif($practise['type'] == "writing_at_end_up")
 @include('practice.writing_at_end_up')
@elseif($practise['type']=="Writing")
 @include('practice.writing')
@elseif($practise['type'] == "writing_at_end_up_listening")
  @include('practice.writing_at_end_up_listening')
@elseif($practise['type'] == "reading_no_blanks_listening")
  @include('practice.reading_no_blanks_listening')
@elseif( $practise['type'] == "true_false_listening" || $practise['type'] == "true_false" )
  @include('practice.true_false_listening')
@elseif($practise['type'] == "listening_writing")
  @include('practice.listening_writing')
@elseif($practise['type'] == "two_table_option_speaking" || $practise['type'] == "three_blank_table_speaking" || $practise['type'] == "three_table_option_speaking" || $practise['type'] == "two_blank_table_speaking_up" || $practise['type'] == "five_blank_table_speaking_up" || $practise['type'] =="four_blank_table_speaking_up")
  @include('practice.blank_tables_speaking')
@elseif($practise['type'] == "speaking_writing")
  @include('practice.speaking_writing')
@elseif($practise['type'] == "speaking_writing_up")
  @include('practice.speaking_writing_up')
@elseif($practise['type'] == "true_false_speaking_simple" )
  @include('practice.true_false_speaking_simple')
@elseif($practise['type'] == "true_false_simple_left_align_listening" ||  $practise['type'] == "true_false_speaking_up")
  @include('practice.true_false_speaking')
@elseif($practise['type'] == "true_false_speaking_writing_simple" )
  @include('practice.true_false_speaking_writing_simple')
@elseif($practise['type'] == "true_false_writing_at_end"  )
  @include('practice.true_false_writing_at_end')
@elseif($practise['type'] == "true_false_writing_at_end_simple" )
  @include('practice.true_false_writing_at_end_simple')
@elseif( $practise['type'] == "underline_text" )
  @if( !empty($practise['is_roleplay']) && $practise['is_roleplay']==1)
    @include('practice.underline_text_roleplay')
  @else
    @include('practice.underline_text')
  @endif
@elseif( $practise['type'] == "underline_text_writing_at_end"  )
  @include('practice.underline_text_writing_at_end')
@elseif( $practise['type'] == "underline_text_writing" )
  @include('practice.underline_text_writing')

@elseif(  $practise['type'] == "writing_at_end_speaking_multiple_up"  )
  @include('practice.writing_at_end_speaking_multiple_up')
@elseif( $practise['type'] == "writing_at_end_speaking_multiple"   || $practise['type'] == "writing_at_end_speaking_multiple_up_listening" )
  @include('practice.writing_at_end_speaking_multiple')

@elseif( $practise['type'] == "multiple_tick")
  @include('practice.multiple_tick')
@elseif($practise['type'] == "set_in_order_vertical_listening")
  @include('practice.set_in_order_vertical_listening')
@elseif($practise['type'] == "set_in_order_vertical")
  @include('practice.set_in_order_vertical')
@elseif($practise['type'] == "true_false_listening_symbol")
  @include('practice.true_false_listening_symbol')
  @elseif($practise['type'] == "multi_choice_question"  || $practise['type'] == "multi_choice_question_listening")
  @include('practice.multi_choice_question')
@elseif($practise['type'] == "writing_at_end_option" )
  @include('practice.writing_at_end_option')
@elseif( $practise['type'] == "writing_at_end")
    @include('practice.writing_at_end')
@elseif( $practise['type'] == "writing_at_end_speaking")
  @include('practice.writing_at_end_speaking')
@elseif($practise['type'] == "reading_no_blanks_no_space")
  @include('practice.reading_no_blanks_no_space')
@elseif($practise['type'] == "listening_speaking" || $practise['type'] == "listening_Speaking")
  @include('practice.listening_speaking')
@elseif( $practise['type'] == "speaking_multiple_up")
  @include('practice.speaking_multiple_up')
@elseif($practise['type'] == "true_false_symbol_reading" )
  @include('practice.true_false_symbol_reading')
@elseif($practise['type'] == "two_blank_table_up_writing_at_end")
  @include('practice.two_blank_table_up_writing_at_end')
@elseif($practise['type'] == "three_blank_table_writing_at_end")
  @include('practice.three_blank_table_writing_at_end')
@elseif($practise['type'] == "writing_at_end_up_speaking_up" || $practise['type'] =="writing_at_end_up_speaking" )
  @include('practice.writing_at_end_up_speaking_up')
@elseif($practise['type'] == "single_image_writing_at_end" )
  @include('practice.single_image_writing_at_end')
@elseif($practise['type'] == "true_false_radio" || $practise['type'] =="true_false_radio_listening" )
  @include('practice.true_false_radio')
@elseif( $practise['type'] == "speaking_multiple_listening" || $practise['type'] == "speaking_multiple" )
  @include('practice.speaking_multiple_listening')
@elseif( $practise['type'] == "match_answer_single_image"
           || $practise['type'] == "match_answer"
           || $practise['type'] == "match_answer_listening"
           || $practise['type'] == "match_answer_image"
           || $practise['type'] == "match_answer_speaking"  )
  @include('practice.match_answer_single_image')
@elseif($practise['type'] == "true_false_listening_simple")
  @include('practice.true_false_listening_simple')
@elseif($practise['type'] == "match_answer_listening_image")
  @include('practice.match_answer_listening_image')
@elseif($practise['type'] == "writing_at_end_up_single_underline_text"  )
  @include('practice.writing_at_end_up_single_underline_text')
@elseif($practise['type'] == "underline_text_multiple"  )
  @include('practice.underline_text_multiple')
@elseif( $practise['type'] == "single_speaking_writing" )
  @include('practice.single_speaking_writing')
@elseif( $practise['type'] == "single_speaking_up_writing")
  @include('practice.single_speaking_up_writing')
@elseif($practise['type'] == "multi_choice_question_multiple" )
  @include('practice.multi_choice_question_multiple')
@elseif($practise['type'] == "single_image_writing_at_end_speaking_up")
  @include('practice.single_image_writing_at_end_speaking_up')
@elseif($practise['type'] == "can_do_statements")
  @include('practice.can_do_statements')
@elseif($practise['type'] == "multi_choice_question_up_writing_at_end" || $practise['type'] == "multi_choice_question_writing_at_end_up_listening")
  @include('practice.multi_choice_question_up_writing_at_end')
@elseif($practise['type'] == "image_box_writing" || $practise['type'] == "image_two_box_writing")
  @include('practice.image_box_writing')
@elseif($practise['type'] == "create_quiz")
  @include('practice.create_quiz')
@elseif($practise['type'] == "conversation_simple_multi_blank")
  @include('practice.conversation_simple_multi_blank')
@elseif($practise['type'] == "listening_tick" || $practise['type'] == "multiple_tick_listening")
  @include('practice.multiple_tick_listening')
@elseif($practise['type'] == "image_reading_no_blanks_no_space")
  @include('practice.image_reading_no_blanks_no_space')
@elseif($practise['type'] == "draw_image_writing")
  @include('practice.draw_image_writing')
@elseif($practise['type'] == "drag_drop")
  @include('practice.drag_drop')
@elseif($practise['type'] == "hide_show_answer_speaking_up")
  @include('practice.hide_show_answer_speaking_up')
@elseif($practise['type'] == "draw_image_speaking")
  @include('practice.draw_image_speaking')
@elseif($practise['type'] == "draw_image_speaking_single_image")
  @include('practice.draw_image_speaking_single_image')
@elseif($practise['type'] == "underline_text_listening" )
  @include('practice.underline_text_listening')
@elseif( $practise['type'] == "true_false_symbol_speaking")
  @include('practice.true_false_symbol_speaking')
@elseif( $practise['type'] == "writing_at_start" )
  @include('practice.writing_at_start')
@elseif( $practise['type'] == "true_false_speaking_up_simple" )
  @include('practice.true_false_speaking_up_simple')
@elseif( $practise['type'] == "writing_at_end_speaking_multiple_record_video" )
  @include('practice.writing_at_end_speaking_multiple_record_video')
@elseif( $practise['type'] == "writing_at_end_up_speaking_multiple_up")
  @include('practice.writing_at_end_up_speaking_multiple_up')
@elseif( $practise['type'] == "writing_at_end_up_speaking_multiple" || $practise['type'] == "writing_at_end_up_speaking_multiple_up")
  @include('practice.writing_at_end_up_speaking_multiple')
@elseif( $practise['type'] == "multi_image_option")
  @include('practice.multi_image_option')
@elseif( $practise['type'] == "multi_image_selection")
  @include('practice.multi_image_selection')
@elseif( $practise['type'] == "multi_image_writing_at_start_up_end")
  @include('practice.multi_image_writing_at_start_up_end')
@elseif( $practise['type'] == "single_speaking_up_conversation_simple_view")
  @include('practice.single_speaking_up_conversation_simple_view')
@elseif( $practise['type'] == "speaking_multiple_single_writing")
  @include('practice.speaking_multiple_single_writing')
@elseif( $practise['type'] == "speaking_multiple_single_image")
  @include('practice.speaking_multiple_single_image')
@elseif( $practise['type'] == "single_image_writing_at_end_speaking")
  @include('practice.single_image_writing_at_end_speaking')
@elseif( $practise['type'] == "set_in_sequence")
  @include('practice.set_in_sequence')
@elseif( $practise['type'] == "multi_choice_question_multiple_speaking")
  @include('practice.multi_choice_question_multiple_speaking')
@elseif( $practise['type'] == "multi_choice_question_writing_at_end_no_option")
  @include('practice.multi_choice_question_writing_at_end_no_option')
@elseif( $practise['type'] == "draw_image_listening" || $practise['type'] == "draw_image")
  @include('practice.draw_image_listening')
@elseif( $practise['type'] == "draw_image_writing_at_end" )
  @include('practice.draw_image_writing_at_end')
@elseif( $practise['type'] == "multi_choice_question_self_marking")
  @include('practice.multi_choice_question_self_marking')
@elseif( $practise['type'] == "underline_text_multi_color"   )
  @include('practice.underline_text_multi_color')
@elseif( $practise['type'] == "single_tick"   )
  @include('practice.single_tick')
@elseif( $practise['type'] == "true_false_a_g"   )
  @include('practice.true_false_a_g')
@elseif( $practise['type'] == "true_false_correct_incorrect"   )
  @include('practice.true_false_correct_incorrect')
@elseif( $practise['type'] == "draw_multiple_image_in_table")
  @include('practice.draw_multiple_image_in_table')
@elseif($practise['type'] == "reading_no_blanks")
  @include('practice.reading_no_blanks')
@elseif($practise['type'] == "reading_no_blanks_movie")
  @include('practice.reading_no_blanks_movie')
@elseif($practise['type'] == "reading_no_blanks_speaking")
  @include('practice.reading_no_blanks_speaking')
@elseif($practise['type'] == "image_reading_total_blanks")
  @include('practice.image_reading_total_blanks')
@elseif($practise['type'] == "reading_total_blanks")
  @include('practice.reading_total_blanks_new')
@elseif($practise['type'] == "reading_total_blanks_speaking" || $practise['type'] == "reading_total_blanks_edit" )
  @include('practice.reading_total_blanks')
@elseif( $practise['type'] == "reading_total_blanks_listening")
  @include('practice.reading_total_blanks_listening')
@elseif($practise['type'] == "reading_blanks")
  @include('practice.reading_blanks')
@elseif($practise['type'] == "reading_no_blanks_speaking_down")
  @include('practice.reading_no_blanks_speaking_down')
@elseif($practise['type'] == "clock_view_speaking")
  @include('practice.clock_view_speaking')
<!-- 
@elseif($practise['type'] == "clock_view_speaking")
  @include('practice.clock_view_speaking') -->
@elseif($practise['type'] == "family_tree")
  @include('practice.family_tree')
@elseif($practise['type'] == "board_game")
  @include('practice.board_game')
@elseif($practise['type'] == "match_answer_single_image_speaking_up")
  @include('practice.match_answer_single_image_speaking_up')
@elseif($practise['type'] == "conversation")
  @include('practice.conversation')
<!-- AES Practice  plesee Don't edit  -->
@elseif($practise['type'] == "conversation_simple_multi_blank_no_submit")
  @include('practice.conversation_simple_multi_blank_no_submit')
@elseif($practise['type'] == "draw_image_writing_email")
  @include('practice.draw_image_writing_email')
@elseif($practise['type'] == "record_video")
  @include('practice.record_video')
@elseif($practise['type'] == "single_tick_reading")
  @include('practice.single_tick_reading')
@elseif($practise['type'] == "single_tick_speaking")
  @include('practice.single_tick_speaking')
@elseif($practise['type'] == "true_false_simple")
  @include('practice.true_false_simple')
@elseif($practise['type'] == "true_false_symbol")
  @include('practice.true_false_symbol')
@elseif($practise['type'] == "true_false_writing_at_end_select_option")
  @include('practice.true_false_writing_at_end_select_option')
@elseif($practise['type'] == "true_false_writing_at_end_all_symbol")
  @include('practice.true_false_writing_at_end_all_symbol')
@elseif($practise['type'] == "hide_show_answer")
  @include('practice.hide_show_answer')
@elseif($practise['type'] == "speaking_up_option")
  @include('practice.speaking_up_option')
@elseif($practise['type'] == "image_reading_no_blanks")
                            @include('practice.image_reading_no_blanks')
@elseif($practise['type'] == "assessment_instructions")
                            @include('practice.assessment_instructions')
@elseif($practise['type'] == "two_blank_table_tapescript")
                            @include('practice.two_blank_table_tapescript')
@elseif($practise['type'] == "three_blank_table_listening_writing")
                            @include('practice.three_blank_table_listening_writing')
@elseif($practise['type'] == "three_blank_table_with_check")
                            @include('practice.three_blank_table_with_check')
@elseif($practise['type'] == "writing_at_end_listening")
                            @include('practice.writing_at_end_listening')
@elseif($practise['type'] == "two_blank_table_listening")
                            @include('practice.two_blank_table_listening')
@elseif($practise['type'] == "three_blank_table_writing_up")
                            @include('practice.three_blank_table_writing_up')

<!-- Amit -->
@elseif($practise['type'] == "true_false_listening_simple")
  @include('practice.true_false_listening_simple')
@elseif($practise['type'] == "multi_choice_question_speaking_up")
  @include('practice.multi_choice_question_speaking_up')
@elseif($practise['type'] == "four_blank_table_speaking_writing")
                            @include('practice.four_blank_table_speaking_writing')
                    
                        @elseif($practise['type'] == "LISTENING")
                            @include('practice.listening')
                        @elseif($practise['type'] == "reading_total_blanks_speaking_up")
                            @include('practice.reading_total_blanks_speaking_up')
                        @elseif($practise['type'] == "single_tick_writing")
                            @include('practice.single_tick_writing')
                        @elseif($practise['type'] == "match_answer_writing")
                            @include('practice.match_answer_writing')
                        @elseif($practise['type'] == "reading_no_blanks_listening_speaking_down")
                            @include('practice.reading_no_blanks_listening_speaking_down')
                        @elseif($practise['type'] == "reading_blank_listening")
                            @include('practice.reading_blank_listening')
                        @elseif($practise['type'] == "multiple_tick_writing")
                            @include('practice.multiple_tick_writing')
                        @elseif($practise['type'] == "underline_text_speaking_down")
                            @include('practice.underline_text_speaking_down')
                        @elseif($practise['type'] == "underline_text_writing_at_end_multi_color")
                            @include('practice.underline_text_writing_at_end_multi_color')
                        @elseif($practise['type'] == "upload_ppt")
                            @include('practice.upload_ppt')
                        @elseif($practise['type'] == "writing_lines")
                            @include('practice.writing_lines')
                        @elseif($practise['type'] == "writing_edit")
  @include('practice.writing_edit')
@elseif($practise['type'] == "writing_word_count")
                            @include('practice.writing_word_count')
@elseif($practise['type'] == "image_writing_at_end_up")
    @include('practice.image_writing_at_end_up')
@elseif($practise['type'] == "writing_at_end_speaking_up")
    @include('practice.writing_at_end_speaking_up')
@elseif( $practise['type'] == "underline_text_image" )
  @include('practice.underline_text_image')
  <!-- --------------- End AES ---------------- -->
@elseif($practise['type'] == "image_box_writing_listening")
   @include('practice.image_box_writing_listening')
@elseif($practise['type'] == "seven_table_option")
  @include('practice.seven_blank_table_speaking')
@else
  <?php echo '<p>'.$practise['type'].'</p>';?>
@endif
